version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  notification-service:
    build: ./notification-service
    ports:
      - "4001:4001"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
